# Generated by Django 3.2.19 on 2023-05-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20230519_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='timpestamp',
            new_name='timestamp',
        ),
    ]
